server:
  port: 8090

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              #          uri: http://localhost:8001
              predicates:
                - Path=/api/v1/products/**
            - id: cart-service
              uri: lb://cart-service
              #           uri: http://localhost:8082
              predicates:
                - Path=/v1/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    enabled: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
